id: P4FC86137
initial_creation_type: input
source_metadata:
  title: Āpastambadharmasūtra
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Dharmaśāstra -- Sūtra
  data entry: Y.Ikari
  contribution to GRETIL: Y.Ikari
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:27:17.039073'
last_modified_at: '2022-03-09T15:27:17.039085'
